# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q2z5sB3ygjYV9b-J3DukxGuDRmJS25_I
"""

-- 📌 SQL CHEAT SHEET - DATA ANALYST RNCP NIVEAU 7 📊

---

# 📥 IMPORTATION ET STRUCTURATION DES DONNÉES

```sql
-- Créer une base de données
CREATE DATABASE my_database;

-- Utiliser une base de données
USE my_database;

-- Créer une table
CREATE TABLE clients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(50),
    age INT,
    ville VARCHAR(50)
);

-- Insérer des données
INSERT INTO clients (nom, age, ville)
VALUES ('Alice', 30, 'Paris'), ('Bob', 25, 'Lyon');

-- Voir les données
SELECT * FROM clients;
```

---

# 🔍 SÉLECTION ET FILTRAGE DES DONNÉES

```sql
-- Sélectionner toutes les colonnes
SELECT * FROM clients;

-- Sélectionner des colonnes spécifiques
SELECT nom, age FROM clients;

-- Filtrer avec une condition
SELECT * FROM clients WHERE age > 25;

-- Utiliser plusieurs conditions
SELECT * FROM clients WHERE age > 25 AND ville = 'Paris';

-- Trier les résultats
SELECT * FROM clients ORDER BY age DESC;
```

---

# 🔄 JOINTURES SQL EXPLIQUÉES

```sql
-- Créer une autre table
CREATE TABLE commandes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    client_id INT,
    montant DECIMAL(10,2),
    date_commande DATE,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Insérer des commandes
INSERT INTO commandes (client_id, montant, date_commande)
VALUES (1, 100.50, '2024-01-10'), (2, 200.75, '2024-01-15');

-- INNER JOIN : Retourne seulement les correspondances
SELECT clients.nom, commandes.montant
FROM clients
INNER JOIN commandes ON clients.id = commandes.client_id;

-- LEFT JOIN : Retourne tous les clients même s'ils n'ont pas de commandes
SELECT clients.nom, commandes.montant
FROM clients
LEFT JOIN commandes ON clients.id = commandes.client_id;

-- RIGHT JOIN : Retourne toutes les commandes même si le client n'existe pas
SELECT clients.nom, commandes.montant
FROM clients
RIGHT JOIN commandes ON clients.id = commandes.client_id;

-- FULL OUTER JOIN : Retourne tous les clients et toutes les commandes
SELECT clients.nom, commandes.montant
FROM clients
FULL OUTER JOIN commandes ON clients.id = commandes.client_id;
```

---

# 📊 AGRÉGATION ET GROUP BY

```sql
-- Compter le nombre de clients
SELECT COUNT(*) FROM clients;

-- Obtenir l'âge moyen des clients
SELECT AVG(age) FROM clients;

-- Regrouper et compter
SELECT ville, COUNT(*) FROM clients GROUP BY ville;

-- Somme des montants des commandes par client
SELECT clients.nom, SUM(commandes.montant)
FROM clients
INNER JOIN commandes ON clients.id = commandes.client_id
GROUP BY clients.nom;
```

---

# 🏎️ OPTIMISATION ET INDEXATION

```sql
-- Ajouter un index pour accélérer les recherches
CREATE INDEX idx_nom ON clients(nom);

-- Voir les indexes existants
SHOW INDEX FROM clients;
```

---

# 📤 EXPORTATION ET IMPORTATION DES DONNÉES

```sql
-- Exporter une table en CSV
SELECT * FROM clients INTO OUTFILE '/tmp/clients.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

-- Importer un fichier CSV dans une table
LOAD DATA INFILE '/tmp/clients.csv'
INTO TABLE clients
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';
```

---

💡 **Astuce :** Cette fiche couvre les **opérations essentielles en SQL**, avec un focus sur les **jointures, agrégations et optimisations**, indispensables pour un **Data Analyst RNCP Niveau 7**. 🚀