# -*- coding: utf-8 -*-
"""WEBSCRAP Sheet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxmzzE5Q2WAsBBCxOR_io1Hgx_r9ztHv
"""

# 📌 Comprendre le Web Scraping en Python

# 🕸️ C'est quoi le Web Scraping ?
# Le Web Scraping est une technique permettant d'extraire automatiquement des données d'un site web.
# Il est utilisé pour collecter des informations en masse, analyser des tendances et créer des bases de données exploitables.

# 📊 Les bibliothèques principales pour le Web Scraping
import requests  # Permet de récupérer le code HTML d'une page web
from bs4 import BeautifulSoup  # Analyse et extrait des données HTML
from selenium import webdriver  # Automatisation des interactions avec un site web
from selenium.webdriver.common.by import By  # Permet de sélectionner des éléments sur une page

# ⚙️ 1. Récupérer une page web avec Requests
# Requests est utilisé pour envoyer une requête à un site web et récupérer son code source HTML.
# C'est la base du Web Scraping car il permet d'obtenir la structure du site.
url = 'https://example.com'  # L'URL de la page que l'on veut scraper
response = requests.get(url)  # Envoi d'une requête HTTP GET au site web
print(response.text)  # Affiche le code HTML de la page récupérée

# 🥣 2. Extraire des éléments précis avec BeautifulSoup
# BeautifulSoup permet d'analyser et de manipuler le code HTML obtenu.
# On va parser le HTML pour extraire des informations spécifiques comme le titre ou un paragraphe.
html = '<html><body><h1>Bienvenue</h1><p class="desc">Ceci est un texte.</p></body></html>'
soup = BeautifulSoup(html, 'html.parser')  # Création de l'objet BeautifulSoup qui va analyser le HTML

# Extraire le titre de la page (élément <h1>)
titre = soup.h1.text  # Accède au premier élément <h1> et récupère son texte
print(titre)  # Affiche 'Bienvenue'

# Extraire un paragraphe spécifique
paragraphe = soup.find('p', class_='desc').text  # Trouve un élément <p> avec la classe 'desc' et récupère son texte
print(paragraphe)  # Affiche 'Ceci est un texte.'

# 🚀 3. Gérer les sites dynamiques avec Selenium
# Certains sites utilisent du JavaScript pour charger du contenu après le chargement initial de la page.
# Selenium permet d'automatiser un navigateur pour récupérer ces données.

browser = webdriver.Chrome()  # Ouvre un navigateur Chrome
browser.get('https://example.com')  # Charge la page web

# Attendre que la page charge complètement et extraire un titre après le rendu du JavaScript
titre_selenium = browser.find_element(By.TAG_NAME, 'h1').text  # Sélectionne l'élément <h1> et récupère son texte
print(titre_selenium)  # Affiche le titre récupéré après le rendu JavaScript

browser.quit()  # Fermer le navigateur une fois le scraping terminé

# ⚠️ 4. Respecter les règles du Web Scraping
# - Toujours vérifier les conditions d'utilisation du site (certains interdisent le scraping)
# - Ne pas scraper trop souvent pour éviter de surcharger un site
# - Ne pas collecter d'informations sensibles (données personnelles, mots de passe, etc.)
# - Vérifier le fichier robots.txt d'un site pour connaître les restrictions (certains bloquent l'accès aux robots)

# 📌 Récapitulatif des étapes du Web Scraping
# 1️⃣ Comprendre la structure HTML d'un site et identifier les données utiles
# 2️⃣ Récupérer la page web avec requests pour obtenir son code HTML
# 3️⃣ Extraire les données avec BeautifulSoup en sélectionnant les bons éléments
# 4️⃣ Gérer les pages dynamiques avec Selenium lorsque le contenu est généré en JavaScript
# 5️⃣ Respecter les règles éthiques et légales du Web Scraping

# En maîtrisant ces bases, tu peux collecter et analyser des tonnes de données facilement ! 🚀